---
abstract: 'Perl bindings to Flickr API'
author:
  - 'Toby Corkindale <tjc@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  LWP::Online: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Flickr-API2
no_index:
  directory:
    - inc
    - t
recommends:
  JSON::XS: 0
requires:
  Compress::Zlib: 0
  Digest::MD5: 0
  HTTP::Message: 1.56
  HTTP::Request: 0
  HTTP::Response: 0
  JSON: 0
  LWP::UserAgent: 0
  Mouse: 0
  Retry: 0
  URI: 1.18
  parent: 0
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 2.03
